faq_page <- tabPanel(
    "FAQ",
    value = "tabFAQ",
    h2("Frequently Asked Questions"),
    bsCollapse(id = "faqPanels_Purpose",
               bsCollapsePanel(strong("What is the purpose of this dashboard?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_Purpose",
                               style = "default")),
    bsCollapse(id = "faqPanels_RegistryFocus",
               bsCollapsePanel(strong("Why did you focus on CT.gov, DRKS, and EUCTR?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_RegistryFocus",
                               style = "default")),
    bsCollapse(id = "faqPanels_SelectionPractices",
               bsCollapsePanel(strong("Why were these practices selected? Are all mandated?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_SelectionPractices",
                               style = "default")),
    bsCollapse(id = "faqPanels_AllPublicationsOfTrial",
               bsCollapsePanel(strong("Does the dashboard reflect all results publications of a given clinical trial?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_AllPublicationsOfTrial",
                               style = "default")),
    bsCollapse(id = "faqPanels_CTIS",
               bsCollapsePanel(strong("Is this relevant given the upcoming launch of EU Clinical Trials Information System?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_CTIS",
                               style = "default")),
    bsCollapse(id = "faqPanels_Responsibility",
               bsCollapsePanel(strong("Is this all the responsibility of trialists and sponsors?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_Responsibility",
                               style = "default")),
    bsCollapse(id = "faqPanels_MoreMethods",
               bsCollapsePanel(strong("Where can I find more about the underlying methods?"),
                               p(HTML("Enter response")),
                               value = "faqPanels_MoreMethods",
                               style = "default")),
)

